### ISSUE TITLE
[FEAT] add derived variables

### ISSUE THREAD

**Issue by jkwag** [boostcampaitech7/level1-classificationinmachinelearning-recsys-10#33]
## Background
- 파생 변수를 추가하고 모델에 쓸 dataframe 생성이 필요합니다

## Todo
- [x] 마켓 관련 파생 변수 추가 
- [x] 네트워크 관련 파생 변수 추가
- [x] MA feature 만들어주는 함수 정의
- [x] Shift feature 만들어주는 함수 정의
- [x] train_df, test_df csv로 추출하는 과정

## See also
- #6
